services:
  webpage:
    build: 
      context: .
      dockerfile: webpage.Dockerfile
    container_name: webpage
    networks:
      - my_network
    
    depends_on:
      - php
    restart: always

  php:
    build: 
      context: .
      dockerfile: php.Dockerfile
    container_name: php-fpm
    networks:
      - my_network
    restart: always

  redpage:
    build: 
      context: .
      dockerfile: redpage.Dockerfile
    container_name: redpage
    networks:
      - my_network
    restart: always

  bluepage:
    build: 
      context: .
      dockerfile: bluepage.Dockerfile
    container_name: bluepage
    networks:
      - my_network
    restart: always

  reverse-proxy:
    build: 
      context: .
      dockerfile: reverse-proxy.Dockerfile
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/cert/:/etc/nginx/cert/:ro,z
      - ./reverse-proxy/cert/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro,z
      - ./logs/:/var/log/nginx/
    networks:
      - my_network
    links:
     - webpage
     - redpage
     - bluepage
    restart: always
  
#  noip:
#    image: ghcr.io/noipcom/noip-duc:latest
#    container_name: noip
#    restart: always
#    env_file:
#      - noip-duc.env
#    volumes:
#      - ./config:/config

networks:
  my_network:
    driver: bridge